spring.application.name: authorization-service
#spring.cloud.config:
#  uri:
#  - http://192.168.99.100:8888
#server.port: 9002
#debug: false
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#eureka.client.service-url:
#  defaultZone: http://192.168.99.100:9000/eureka/
#spring.cloud:
#  discovery:
#    client:
#      health-indicator:
#        enabled: true
#        include-description: true
#spring.zipkin.base-url: http://192.168.99.100:9411/
#spring.sleuth.sampler.probability: 1

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    pool-name: SpringBootHikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth?useSSL=false&charset=utf8
    username: jamie
    password: Hsbc1234
    initialization-mode: always
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 5
      idle-timeout: 30000
      minimum-idle: 2
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect