spring.application.name: authorization-service
#spring.cloud.config:
#  uri:
#  - http://192.168.99.100:8888
server.port: 8080
server:  servlet:    context-path: /uaa
  use-forward-headers: false
debug: false
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'

eureka.client.service-url:
  defaultZone: http://localhost:8761/eureka/
spring.cloud:
  discovery:
    client:
      health-indicator:
        enabled: true
        include-description: true
#spring.zipkin.base-url: http://192.168.99.100:9411/
#spring.sleuth.sampler.probability: 1

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    pool-name: SpringBootHikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:3306/oauth?useSSL=false&charset=utf8
    username: jamie
    password: Hsbc1234
    initialization-mode: always
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 5
      idle-timeout: 30000
      minimum-idle: 2
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    
security.oauth2.jwt.key-pair:
  store-pass: Test1234
  alias: internal-certs
  file-path: keystore.p12
      